### ISSUE TITLE
thanks for this awesome mod

### ISSUE THREAD

**Issue by perdakovich** [ArchUsr64/toggle_perspective_fixed#1]
just wanted to say thanks, cause this mod really helped me. kinda off-topic, but:

can you share your modpack for 1.8.9, so I could find more cool mods like this one? 
Trying to switch from new versions to 1.8.9 (only to play pvp servers like Hypixel)

**Comment by ArchUsr64** [comment]
Here you go, [mods.zip](https://github.com/ArchUsr64/toggle_perspective_fixed/files/11780753/mods.zip)

**Comment by perdakovich** [comment]
thanks! doesn't betterfps conflict with optifine?
